# Generated by Django 5.2.7 on 2025-12-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
    ]
