# Generated by Django 5.2.5 on 2026-03-10 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_remove_cart_customer_remove_cart_menu_item_and_more'),
        ('restaurants', '0009_alter_restaurant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.menuitem'),
        ),
    ]
